### ISSUE TITLE
Examples?

### ISSUE THREAD

**Issue by NerdGuruDevelopers** [Pessimistress/minecraft-chunk-viewer#10]
Do you happen to have some examples for loading up different (and multiple) mca files?

Do you need to run node to use this? I presume so to update the blocks (based on another ticket), but what about for embedded use?

I'd like to use your code to load up a few chunks and rotate around a build.

**Comment by rmackinnon** [comment]
Greetings,

>>Do you happen to have some examples for loading up different (and multiple) mca files?

The tool was only designed and implemented to open one region file at a time. You need to drag and drop the region file from your local install into the browser window to do so.  This works on the [Demo site](http://pessimistress.github.io/minecraft/).

Early on the feature to select multiple chunks was requested and shipped, allowing someone to select/view/rotate around a decently large selection of chunks.  You can enable this feature by pressing "shift" while left clicking chunks on the region mini-map.

>>Do you need to run node to use this? I presume so to update the blocks (based on another ticket), but what about for embedded use?

NodeJS is needed to compile the source to create the static javascript webpack. Once compiled, only a web browser with webgl is needed for it to work. Correct there are scripts for updating the block types, creating the webgl textures, etc.

>>I'd like to use your code to load up a few chunks and rotate around a build.

One day we'd like to have a server side feature/daemon to allow loading parts of the map. One day...

--Rob

**Comment by NerdGuruDevelopers** [comment]
Is there a way to select chunks using javascript and create an auto rotate? 

Is there a way to load up different mca files using javascript?

**Comment by rmackinnon** [comment]
Either of these things are not currently on the road map, maybe at some
point in the future. Unless you have idea, we would be happy to review a PR
for this feature, otherwise you are requesting something that does not
exist and is not planned to be in existence any time soon.
